###
GET https://broadcast.bnorm.dev/channels/story-kc25/subscribe
Accept: text/event-stream

###
GET https://broadcast.bnorm.dev/channels/story-kc25-react/subscribe
Accept: text/event-stream

###
GET https://broadcast.bnorm.dev/channels
Authorization: Bearer {{$env.BROADCAST_TOKEN}}
Accept: application/json

###
DELETE https://broadcast.bnorm.dev/channels/story-kc25
Authorization: Bearer {{$env.BROADCAST_TOKEN}}
